name: "infra"

services:
  
####################
# Back End Services
####################

  socky_proxy:
    container_name: socky_proxy
    image: lscr.io/linuxserver/socket-proxy:latest

    read_only: true
    tmpfs:
      - /run
  
    networks:
      - socky_proxy-net

    ports:
      - ${PORT_SOCKY_PROXY}:2375


    environment:
      # Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc).
      #   0 - revoke access
      #   1 - grant access
      ALLOW_START: 0 #
      ALLOW_STOP: 0 #
      ALLOW_RESTARTS: 0 #
      AUTH: 0 #
      BUILD: 0 #
      COMMIT: 0 #
      CONFIGS: 0 #
      CONTAINERS: 1 # crowdsec, homepage. dozzle
      DISABLE_IPV6: 0 #
      DISTRIBUTION: 0 #
      EVENTS: 1 #
      EXEC: 0 #
      IMAGES: 1 # 
      INFO: 1 # crowdsec
      LOG_LEVEL: info #
      NETWORKS: 0 #
      NODES: 0 #
      PING: 1 #
      PLUGINS: 0 #
      POST: 0 #
      SECRETS: 0 #
      SERVICES: 0 #
      SESSION: 0 #
      SWARM: 0 #
      SYSTEM: 0 #
      TASKS: 0 #
      TZ: ${TZ}
      VERSION: 1 #
      VOLUMES: 0 #

    labels:
      - homepage.group=Back End
      - homepage.icon=tsd-proxy
      - homepage.name=Docker Socket Proxy

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    healthcheck:
      test: wget --spider http://${SERVER_URL}:${PORT_SOCKY_PROXY}/version || exit 1
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "30s"

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M

    restart: always


####################
# Docker Environment
####################

networks:
  socky_proxy-net:
    name: socky_proxy-net
    external: true
