version: "3.7"

services:

  tandoor_db:
    container_name: tandoor_db
    image: postgres:11-apline

    networks:
      - tandoor-net

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: tandoor #TODO env #creates the specified user with superuser power and a database with the same name
      POSTGRES_PASSWORD: #TODO env #the superuser password for PostgreSQL
      POSTGRES_DB:  #TODO env #optional. Sets db created image is first started. Defaults to POSTGRES_USER if unset

    volumes:
      - ~/server/db/tandoor:/var/lib/postgresql/data #TODO env

    restart: always

  adminer:
    image: adminer
    restart: always
    depends_on:
      - tandoor_db
    
    networks:
      - tandoor-net

    ports:
      - 8081:8080 #TODO env

    environment:
      ADMINER_DESIGN: 'dracula' #TODO env

    links:
      - tandoor_db:db
  
  tandoor:
    container_name: tandoor
    image: vabene1111/recipes:1.0.8

    depends_on:
      - tandoor_db

    networks:
      - tandoor-net

    ports:
      - 82:8080 #TODO env

    environment:
      SECRET_KEY: # Required. random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
      TIMEZONE: America/Chicago #TODO env ${TZ}
      DEBUG: 0

      # Database
      DB_ENGINE: django.db.backends.postgresql
      # DB_OPTIONS: {} # e.g. {"sslmode":"require"} to enable ssl
      POSTGRES_HOST: 'db' #TODO env
      POSTGRES_PORT: 5432 #TODO env
      POSTGRES_USER: 'tandoor' #TODO env
      POSTGRES_PASSWORD: #Required. #TODO env
      POSTGRES_DB: tandoordb #TODO env

      # database connection string, when used overrides other database settings.
      # format might vary depending on backend
      # DATABASE_URL = engine://username:password@host:port/dbname

      FRACTION_PREF_DEFAULT: 1 #default value for the user preference 'fractions'
      COMMENT_PREF_DEFAULT: 0 #enable/disable commenting system

    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - tandoor-media:/opt/recipes/mediafiles

      
networks:
  tandoor-net:
    name: tandoor-net

volumes:
  tandoor-static:
  tandoor-media: