version: "3.7"

services:

  tandoor_db:
    container_name: tandoor_db
    image: postgres:11-apline

    networks:
      - tandoor-net

    environment:
      POSTGRES_USER: root #TODO env #creates the specified user with superuser power and a database with the same name
      POSTGRES_PASSWORD: #TODO env #the superuser password for PostgreSQL
      POSTGRES_DB:  #TODO env #optional. Sets db created image is first started. Defaults to POSTGRES_USER if unset

    volumes:
      - ~/server/db/tandoor:/var/lib/postgresql/data #TODO env

    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

networks:
  tandoor-net:
    name: tandoor-net

  #tandoor:
  #  container_name: tandoor
  #  image: vabene1111/recipes:1.0.8
#
  #  depends_on:
  #  
  #  networks:
  #  ports:
#
  #  environment:
  #    SECRET_KEY: # Required. random secret key, use for example `base64 /dev/urandom | head -c50` to generate one
  #    TIMEZONE: America/Chicago ${TZ}
#
  #    # Database
  #    DB_ENGINE: django.db.backends.postgresql
  #    # DB_OPTIONS: {} # e.g. {"sslmode":"require"} to enable ssl
  #    POSTGRES_HOST: 'db_recipes'
  #    POSTGRES_PORT: 5432
  #    POSTGRES_USER: 'tandoor'
  #    POSTGRES_PASSWORD: #Required.
  #    POSTGRES_DB=tandoordb
#
  #    # database connection string, when used overrides other database settings.
  #    # format might vary depending on backend
  #    # DATABASE_URL = engine://username:password@host:port/dbname
#
  #  volumes:
  #    - 