version: "3.7"

services:

  tandoor_db:
    container_name: tandoor_db
    image: postgres:11-alpine

    networks:
      - tandoor-net

    ports:
      - ${PORT_POSTGRES}:5432

    env_file:
      - ./env/tandoor.env

    volumes:
      - ${DBDIR}/tandoor:/var/lib/postgresql/data

    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 96M
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    
    depends_on:
      - tandoor_db
    
    networks:
      - tandoor-net

    ports:
      - ${PORT_ADMINER}:8080

    environment:
      ADMINER_DESIGN: 'dracula' #TODO env

    links:
      - tandoor_db:db
  
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 32M
    restart: unless-stopped
  
  tandoor:
    container_name: tandoor
    image: vabene1111/recipes:1.0.8

    depends_on:
      - tandoor_db

    networks:
      - tandoor-net

    ports:
      - ${PORT_RECIPE}:8080

    env_file:
      - ./env/tandoor.env

    environment:
      TIMEZONE: ${TZ}
      POSTGRES_PORT: ${PORT_POSTGRES}

    links:
      - tandoor_db:db

    volumes:
      - tandoor-static:/opt/recipes/staticfiles
      - tandoor-media:/opt/recipes/mediafiles
    
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    restart: unless-stopped

networks:
  tandoor-net:
    name: tandoor-net

volumes:
  tandoor-static:
  tandoor-media: