version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 8001:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/portainer/data:/data
      - ${CONFIGDIR}/shared:/shared
    environment:
      TZ: ${TZ}

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 23 * * SUN" --cleanup

  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma
    restart: always
    ports:
      - ${PORT_UPKUMA}:3001
    volumes:
      - ${CONFIGDIR}/uptime-kuma:/app/data


  


networks:
  web:
    external: true
