version: "3.7"

services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 8001:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/portainer/data:/data
      - ${CONFIGDIR}/shared:/shared
    environment:
      TZ: ${TZ}

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 23 * * SUN" --cleanup

  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma:latest
    restart: always
    ports:
      - ${PORT_UPKUMA}:3001
    volumes:
      - ${CONFIGDIR}/uptime-kuma:/app/data

  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns:latest
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUBDOMAINS: ${DUCKDNS_SUBDOMAINLIST}
      TOKEN: ${DUCKDNS_TOKEN}
      LOG_FILE: ${LOGDIR}/duckdns.log
    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional
    restart: unless-stopped

  bitwarden:
    container_name: bitwarden
    image: vaultwarden/server
    restart: unless-stopped
    ports:
      - ${PORT_BITWARDEN_HTTP}:80
      #- ${PORT_BITWARDEN_HTTPS}:443
    volumes:
      - ${CONFIGDIR}/bw-data:/data
    environment:
      TZ: ${TZ}
      LOG_FILE: ${LOGDIR}/bitwarden.log
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'false'   # set to false to disable signups
      INVITATIONS_ALLOWED: 'false'
  

  caddy:
    container_name: caddy
    image: caddy/caddy:alpine
    restart: unless-stopped
    ports:
        - ${PORT_CADDY_HTTP}:80
        - ${PORT_CADDY_HTTPS}:443
    networks:
        - web
    volumes:
      - ${CONFIGDIR}/caddy/caddyfile:/etc/caddy/Caddyfile
      - ${CONFIGDIR}/caddy/data:/data # Optional, house for certs
      - ${CONFIGDIR}/caddy/config:/config # Optional, JSON Config files
    environment:
      LOG_FILE: ${LOGDIR}/caddy.log
      DOMAIN: ${DOMAIN}
      EMAIL: ${EMAIL_ADMIN}

networks:
  web:
    external: true

volumes:
  
