version: "3.7"

services:
  
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - 8001:8000
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${CONFIGDIR}/data:/data
      - ${CONFIGDIR}/_shared:/shared
    environment:
      - TZ=${TZ}
  
  organizr:
    container_name: organizr
    image: organizr/organizr
    restart: always
    volumes:
      - ${CONFIGDIR}/organizr:/config
      - ${CONFIGDIR}/_shared:/shared
    ports:
      - 81:80
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 23 * * SUN" --cleanup

  uptime-kuma:
    container_name: uptime_kuma
    image: louislam/uptime-kuma
    restart: always
    ports:
      - 9001:3001
    volumes:
      - ${CONFIGDIR}/uptime-kuma:/app/data

  duckdns:
    container_name: duckdns
    image: ghcr.io/linuxserver/duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=${DUCKDNS_SUBDOMAINLIST}
      - TOKEN=${DUCKDNS_TOKEN}
      - LOG_FILE=${DEBUG_LOG}
    volumes:
      - ${CONFIGDIR}/duckdns:/config #optional
    restart: unless-stopped
