server {
    listen 80;
    server_name localhost;
    client_max_body_size 16M;

    # serve static files
    location /static/ {
        alias /static/;
    }

    # serve media files
    location /media/ {
        alias /media/;
    }

    # pass requests for dynamic content to gunicorn
    location / {
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://tandoor:8080;

        error_page 502 /errors/http502.html;
    }

    location /errors/ {
        alias /etc/nginx/conf.d/errorpages/;
        internal;
    }
}

# https://github.com/TandoorRecipes/recipes/blob/develop/nginx/conf.d/Recipes.conf