name: "image-board"

services:

####################
# Pinry
####################

  pinry:
    container_name: pinry
    image: getpinry/pinry:latest

    networks:
      - caddy-net

    ports:
      - ${PORT_PINRY}:80

    environment:
      ALLOW_NEW_REGISTRATIONS: 'True'
      SECRET_KEY: ${PINRY_SECRETKEY}
    
    labels:
      - diun.enable=true
      - homepage.group=Lifestyle
      - homepage.name=Pinry
      - homepage.icon=pinry
      - homepage.href=http://${EXTERNAL_PINRY}.${DOMAIN}
      - homepage.description=Save, tag, and share images, videos and webpages

    volumes:
      - ${CONFIGDIR}/pinry:/data
    
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    restart: unless-stopped

networks:
  caddy-net:
    name: caddy-net
    external: true