name: "change-detect"

services:

####################
# PriceBuddy
####################

  pricebuddy:
    image: ghcr.io/jez500/pricebuddy:latest
    container_name: pricebuddy

    depends_on:
      pricebuddy-db:
        condition: service_started

    ports:
      - ${PORT_PRICEBUDDY}:80

    environment:
      PUID: ${PUID}
      GUID: ${PGID
      TZ: ${TZ}

      APP_TIMEZONE: ${TZ}
      APP_ENV: local
      APP_DEBUG: false

      DB_HOST: pricebuddy_db                  # Name of the database service
      DB_USERNAME: ${PRICEBUDDY_DB_USERNAME}  # Should match the MYSQL_USER in the database service
      DB_PASSWORD: ${PRICEBUDDY_DB_PASSWORD}  # Should match the MYSQL_PASSWORD in the database service
      DB_DATABASE: ${PRICEBUDDY_DB}           # Should match the MYSQL_DATABASE in the database service
      
      APP_KEY: ${PRICEBUDDY_APPKEY}
      APP_USER_EMAIL: ${PRICEBUDDY_ADMIN_EMAIL}       # Only used for seeding the database
      APP_USER_PASSWORD: ${PRICEBUDDY_ADMIN_PASSWORD} # Only used for seeding the database
      #SCRAPER_BASE_URL:    # Url to Name of the scrapper service
      AFFILIATE_ENABLED: 'true'               # See https://pricebuddy.jez.me/support-project.html

    labels:
      - homepage.group=Lifestyle
      - homepage.name=Pricebuddy
      - homepage.icon=price-buddy
      - homepage.href=http://${SERVER_URL}:${PORT_PRICEBUDDY}


    volumes:
      - pricebuddy_storage:/app/storage

  pricebuddy_db:
    image: lscr.io/linuxserver/mariadb:latest
    container_name: pricebuddy_db

    environment:
      PUID: ${PUID}
      GUID: ${PGID}
      TZ: ${TZ}

      #NOTE changing any of the MYSQL_ variables after the container has set up the initial databases has no effect, use the mysqladmin tool or cli to make changes.
      MYSQL_DATABASE: ${PRICEBUDDY_DB}
      MYSQL_USER: ${PRICEBUDDY_DB_USERNAME}
      MYSQL_PASSWORD: ${PRICEBUDDY_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${PRICEBUDDY_DB_ROOT_PASSWORD}

    labels:
      - homepage.group=Databases
      - homepage.name=Pricebuddy | MariaDB
      - homepage.icon=mariadb
      - dockpeek.tags=db

    volumes:
      - ${DIR_DB}/pricebuddy_mariadb:/config

volumes:
  pricebuddy_storage: